title: Шагапов Алексей Александрович
description: >-
  Место рождения – Забайкальский край, город Чита. Обучался в школе на отметки «удовлетворительно». Окончил Институт космических и информационных технологий в городе Красноярске. После окончания Института, по предложению военного комиссариата проходил обучение в школе ФСБ в городе Новосибирске. Оперуполномоченный УФСБ по Красноярскому краю в звании старшего лейтенанта. Места прохождения службы - Железногорск, Зеленогорск, Канск. На данный момент проходит службу в городе Канске, курирует Иланский район. Внешне спокоен, опрятен, при общении напряжен, при недовольстве отвечает агрессивно, трудности в построении конструктивного диалога.  Присутствуют обманы понимания. Лицемерен. Не женат. Детей нет. Не способен выстроить отношения в рабочем коллективе
author: 
  name: Алексей Шагапов
  
logo: /assets/img/0001.jpg

social:
  name: Алексей Шагапов
  links:
    - https://vk.com/id31062832


baseurl: ""

show_downloads: false

timezone: Russia/Moscow
lang: ru-RU
theme: jekyll-theme-minimal

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

gems:
  - jekyll-seo-tag
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-avatar
  - jekyll-github-metadata